[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=00000000000000000000000000000000
ProjectName=Project Bullet Hell
CompanyName=

[/Script/Engine.Engine]
GameEngine=/Script/Engine.GameEngine
GameViewportClientClassName=/Script/Engine.GameViewportClient

[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Game/_Game/Levels/Greybox/L_Greybox_Test
EditorStartupMap=/Game/_Game/Levels/Greybox/L_Greybox_Test
GlobalDefaultGameMode=/Script/ProjectBulletHell.PBHGameMode

[/Script/Engine.PhysicsSettings]
DefaultGravityZ=-980.0
bEnableEnhancedDeterminism=False

[/Script/GameplayAbilities.AbilitySystemGlobals]
bIgnoreAbilitySystemCooldowns=False

; Enhanced Input becomes the default input system in recent engine versions,
; this just makes it explicit for clarity/future-proofing.

[/Script/EnhancedInput.EnhancedInputDeveloperSettings]
DefaultPlayerInputClass=/Script/EnhancedInput.EnhancedPlayerInput
DefaultInputComponentClass=/Script/EnhancedInput.EnhancedInputComponent

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=6159653D41BD1F86AC07F88ECC0CAD90
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=

